In [2]:
import numpy as np 

# Scaler , Vector , Matrix , Tensor 


In [3]:
Scaler = 5.0 
print(Scaler)
print("Type of Scaler" , type(Scaler))
print("-"*40)

5.0
Type of Scaler <class 'float'>
----------------------------------------


In [4]:
vector = np.array( 
    [3,7,2]
)
print("Vector", vector)
print("Shape of Vector:" , vector.shape)
print("-"*40)

Vector [3 7 2]
Shape of Vector: (3,)
----------------------------------------


In [5]:
matrix = np.array(
    [
    [4,5,6],
    [6,7,8]
    ]
)
print("The Matrix : " ,matrix)
print("Type of matrix : ", type(matrix))
print("Shape of Matrix : " ,matrix.shape)
print("-"*40)

The Matrix :  [[4 5 6]
 [6 7 8]]
Type of matrix :  <class 'numpy.ndarray'>
Shape of Matrix :  (2, 3)
----------------------------------------


In [6]:
tensor = np.array ([
    [
        [1,2,3],
        [4,5,6]
    ]
    ,
    [
        [11,12,13]
        ,
        [13,14,15]
    ]
    
])
print("tensor : " , tensor ) 
print("Shape of tensor : " , tensor.shape )
print("Type of tensor : " , type(tensor)) 
print("-"*40)

tensor :  [[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [13 14 15]]]
Shape of tensor :  (2, 2, 3)
Type of tensor :  <class 'numpy.ndarray'>
----------------------------------------


# Creating Vector and matrix for M.L Style Data



In [7]:
x = np.array(
    [
        [2,30],# Sample 1
        [5,80],# Sample 2
        [1,20]  #Sample 3 
    ]
)
y = np.array([0,1,0])
print("Input Data matrix X :\n" ,x)
print("X shape: " , x.shape)
                  #(n_sample ,n_features) 
print("Output vector y:\n" , y)
print("y shape :", y.shape)
                  # (n_samples)
# A single sample as a vector 
x1 = x[0]  # first row 
print("\n First sample as a vector : "  , x1)
print("x1 shape : " , x1.shape ) 

Input Data matrix X :
 [[ 2 30]
 [ 5 80]
 [ 1 20]]
X shape:  (3, 2)
Output vector y:
 [0 1 0]
y shape : (3,)

 First sample as a vector :  [ 2 30]
x1 shape :  (2,)


# Basic Operation : Addition ,Scaler , Multiplication , transpose 

Two Vectors with same length

In [9]:
v1 = np.array([1,2,3]) 
v2 = np.array([4,5,6])
print("v1:",v1)
print("v2:",v2)

v1: [1 2 3]
v2: [4 5 6]


Vector addition 

In [11]:
v_add = v1+v2
print("\n Vector addition v1 + v2:" , v_add)


 Vector addition v1 + v2: [5 7 9]


Scaler Multiplication

In [12]:
v1_scaled = 2*v1
print("Scaler multiplication 2*v1:" ,v1_scaled)

Scaler multiplication 2*v1: [2 4 6]


# Matrix Multiplication 

In [13]:
a = np.array(
    [
        [1,2],
        [3,4]
    ])
b = np.array(
    [
        [10,20],
        [30,40]
    ])

In [14]:
print("\n Matrix A:\n",a)
print("Matrix B:\n" , b)


 Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[10 20]
 [30 40]]


Matrix Addition

In [15]:
a_add_b = a+b
print("\n matrix addition a+b:\n", a_add_b)


 matrix addition a+b:
 [[11 22]
 [33 44]]


Scaler Multiplication

In [18]:
a_scaled = 0.5*a
print("Scaler multiplication 0.5*A:\n" , a_scaled)


Scaler multiplication 0.5*A:
 [[0.5 1. ]
 [1.5 2. ]]


Transpose

In [19]:
a_t = a.T 
print("\n Transpose of A:\n" ,a_t)
print("a shape:" , a.shape," (a.t shape :", a_t.shape)


 Transpose of A:
 [[1 3]
 [2 4]]
a shape: (2, 2)  (a.t shape : (2, 2)
