In [1]:
import numpy as np 

In [6]:
# Single Number Value 
scaler = 5.0
print (scaler)
print(type(scaler))


5.0
<class 'float'>


In [8]:
# 1d Data or Multiple Number of value in a Single bracket 
vector = np.array(
    [1,2,3,4,5]
)
print(vector)

[1 2 3 4 5]


In [12]:
# 2d Data or Data with rows and column 
mat = np.array(
    [
    [1,2,3,4,5],
    [2,3,4,5,6]
    ]
)
print(type(mat))
print(mat)
print(mat.shape)

<class 'numpy.ndarray'>
[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)
